### ISSUE TITLE
Features about pet adoption

### ISSUE THREAD

**Issue by dandan1232** [MixJade/MixPet#2]
Hello~~, this is a great project and the documentation is very detailed and awesome. But I'm currently encountering a small problem, please let me know.
1. The UI of this project is very cool. What components are used?
2. When I try to click on the details of "Pet for Adoption" from the user's perspective, a pop-up window will inform: The system is busy, please try again later. But when I click to apply for adoption, the button will change to Under review. However, when I switch to the administrator's page and click on the adoption module, the system is busy, please try again later. I suspect there is a problem with this interface.
![image](https://github.com/user-attachments/assets/5bcb4e9e-77cb-4e4c-943c-f3047736e270)

![image](https://github.com/user-attachments/assets/7ced3097-05cf-425a-9444-daefa8722b8f)

**Comment by MixJade** [comment]
1. Element-Plus
2. 看看你的数据库里有没有"adopt"这张表，或者说，你是否是在名为pet_ship的数据库中完整的运行了pet_ship.sql这个文件
3. 如果以上没有解决问题，且你是中国人的话，可以考虑加微信，用腾讯会议来看看

**Comment by dandan1232** [comment]
感谢你，我成功解决了问题，你的回答很及时，但是我刚刚在测试的时候，发现不管是用户或者是管理者，点击聊天按钮，会第一时间出现弹框：您已离开聊天页面，这是相对于上一次，所以在每一次重新进去此页面的时候，都会有这样的一个弹框提示吗？

另外，如果可以，我希望与你成为朋友，this is my wechat：waitu1232

**Comment by MixJade** [comment]
是在离开聊天页面后会弹窗提示，我估计是你退出之后再点击的间隔太短了
